@ECHO off
REM This script allows an iSystem winIDEA IDE to use cymcuelftool to perform
REM the post processing that is necessary to update the *.elf file
REM generated by the linker into a complete memory image to use in
REM programming the PSoC.
REM Before call cymcuelftool, to ensure that CM0+ program is generated, the
REM CM0+ project is launched from this script.

SET CMPDIR=%1
SET OUTPUTPATH=%2
SET OUTPUTNOEXT=%3
SET IRFDIR=%4
IF [%5] == [] GOTO single_core (
SET EXEDIR=%5
)
IF [%6] == [] GOTO single_core (
SET TARGETNAME=%6
)
IF [%7] == [] GOTO single_core (
SET MODE=%7
)

:dual_core
ECHO.
ECHO Building CM0p project
%EXEDIR%\winideaBuild.exe %IRFDIR%\..\..\cm0plus\isystem\FreeRTOS_Basic_cm0plus.xqrf %TARGETNAME% /rebuild
IF %errorlevel% NEQ 0 EXIT /b %errorlevel%
ECHO.
ECHO Merging CM0p program with CM4 program into complete memory image
%IRFDIR%\..\..\..\..\..\..\tools\win\elf\cymcuelftool.exe --merge %OUTPUTPATH% %IRFDIR%\..\..\cm0plus\isystem\%MODE%\FreeRTOS_Basic_cm0plus.elf --output %OUTPUTPATH%
IF %errorlevel% NEQ 0 EXIT /b %errorlevel%
GOTO generate_srec

:single_core
ECHO.
ECHO Conversion CM4 program into complete memory image
%IRFDIR%\..\..\..\..\..\..\tools\win\elf\cymcuelftool.exe --sign %OUTPUTPATH% --output %OUTPUTPATH%
IF %errorlevel% NEQ 0 EXIT /b %errorlevel%

:generate_srec
ECHO.
ECHO Generating .srec file
%CMPDIR%bin\arm-none-eabi-objcopy.exe -O srec %OUTPUTPATH% %OUTPUTNOEXT%.srec
ECHO Post build step finished succesfully
EXIT
