@echo off
REM This script allows an iSystem winIDEA IDE to use CyMCUElfTool to perform
REM the post processing that is necessary to update the *.elf file
REM generated by the linker into a complete memory image to use in
REM programming the PSoC.

SET CMPDIR=%1
SET OUTPUTPATH=%2
SET OUTPUTNOEXT=%3
SET IRFDIR=%4

ECHO.
ECHO Conversion CM0p program into complete memory image
%IRFDIR%\..\..\..\..\..\..\tools\win\elf\cymcuelftool.exe --sign %OUTPUTPATH% --output %OUTPUTPATH%
IF %errorlevel% NEQ 0 EXIT /b %errorlevel%

ECHO.
ECHO Generating .srec file
%CMPDIR%bin\arm-none-eabi-objcopy.exe -O srec %OUTPUTPATH% %OUTPUTNOEXT%.srec
ECHO Post build step finished successfully
